Rewrite logic so that Vivado does not throw an error during simulation.
Although entity was synthesizable Vivado was throwing following error
when starting simulation data flow analysis before behavioral
simulation:
ERROR: [XSIM 43-3312] Signal SIGABRT received.